############################################################
# Image Processing configuration parameters
############################################################

camera_name PiCam

# Raspberry Pi Camera (CSI)
video_device /dev/video2

# Image width in pixels.
width 640

# Image height in pixels.
height 480

# Maximum number of frames to be captured per second.
framerate 30
emulate_motion on

# Text to be overlayed in the lower left corner of images
text_left CAMERA 2\n%{fps} FPS

# Text to be overlayed in the lower right corner of images.
text_right %Y-%m-%d\n%T-%q

v4l2_palette 17    # YUYV
stream_port 8002
webcontrol_port 8012
