############################################################
# Image Processing configuration parameters
############################################################

camera_name USBcam

# USB Webcam
video_device /dev/video0

# Image width in pixels.
width 640

# Image height in pixels.
height 480

# Maximum number of frames to be captured per second.
framerate 30
emulate_motion on

# Text to be overlayed in the lower left corner of images
text_left CAMERA 1\n%{fps} FPS

# Text to be overlayed in the lower right corner of images.
text_right %Y-%m-%d\n%T-%q

v4l2_palette 17
stream_port 8001
webcontrol_port 8011
